### ISSUE TITLE
Test failure while building

### ISSUE THREAD

**Issue by seqizz** [cool-RR/python_toolbox#3]
I'm trying to package pysnooper to the nixos, and since python_toolbox is a dependency, that's also in the list.
Here is my output of tests, most of them are ok but I thought you'd like the check failures:

```
======================================================================
ERROR: test_python_toolbox.test_combi.test_extensive.test_1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in <genexpr>
    for m in range(self.sequence_length)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/grbf0f7g04mvhjv6yvgh26nmcv4iddbi-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in test_1
  File "<string>", line 1, in <lambda>
  File "/build/python_toolbox-0.9.3/source_py3/test_python_toolbox/test_combi/test_extensive.py", line 223, in _check_variation_selection
    assert perm_space.index(perm_space[-1]) == perm_space.length - 1
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in __getitem__
    for m in range(self.sequence_length)
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_python_toolbox.test_combi.test_extensive.test_2
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in <genexpr>
    for m in range(self.sequence_length)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/grbf0f7g04mvhjv6yvgh26nmcv4iddbi-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in test_2
  File "<string>", line 1, in <lambda>
  File "/build/python_toolbox-0.9.3/source_py3/test_python_toolbox/test_combi/test_extensive.py", line 223, in _check_variation_selection
    assert perm_space.index(perm_space[-1]) == perm_space.length - 1
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 556, in __getitem__
    return self.perm_type(self.undapplied[i], perm_space=self)
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in __getitem__
    for m in range(self.sequence_length)
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_python_toolbox.test_combi.test_extensive.test_5
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in <genexpr>
    for m in range(self.sequence_length)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/grbf0f7g04mvhjv6yvgh26nmcv4iddbi-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in test_5
  File "<string>", line 1, in <lambda>
  File "/build/python_toolbox-0.9.3/source_py3/test_python_toolbox/test_combi/test_extensive.py", line 223, in _check_variation_selection
    assert perm_space.index(perm_space[-1]) == perm_space.length - 1
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in __getitem__
    for m in range(self.sequence_length)
RuntimeError: generator raised StopIteration

======================================================================
ERROR: test_python_toolbox.test_combi.test_extensive.test_6
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in <genexpr>
    for m in range(self.sequence_length)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/nix/store/grbf0f7g04mvhjv6yvgh26nmcv4iddbi-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "<string>", line 1, in test_6
  File "<string>", line 1, in <lambda>
  File "/build/python_toolbox-0.9.3/source_py3/test_python_toolbox/test_combi/test_extensive.py", line 223, in _check_variation_selection
    assert perm_space.index(perm_space[-1]) == perm_space.length - 1
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 554, in __getitem__
    return self.unsliced[i + self.canonical_slice.start]
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/combi/perming/perm_space.py", line 687, in __getitem__
    for m in range(self.sequence_length)
RuntimeError: generator raised StopIteration

======================================================================
FAIL: test_python_toolbox.test_cute_testing.test_raise_assertor.test_assert_exact_type
Test `RaiseAssertor`'s `assert_exact_type` option.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/grbf0f7g04mvhjv6yvgh26nmcv4iddbi-python3.7-nose-1.3.7/lib/python3.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/build/python_toolbox-0.9.3/source_py3/test_python_toolbox/test_cute_testing/test_raise_assertor.py", line 112, in test_assert_exact_type
    raise KeyError("Look at me, I'm a KeyError")
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/context_management/context_manager.py", line 107, in __exit_using_manage_context
    generator.throw(exc_value.with_traceback(exc_traceback))
  File "/build/python_toolbox-0.9.3/source_py3/python_toolbox/cute_testing.py", line 91, in manage_context
    (self.exception_type.__name__, repr(self.text))
python_toolbox.cute_testing.Failure: A `Failure` was raised but 'The exception `KeyError("Look at me, I\'m a KeyError",)` was raised, and it *is* an instance of the `LookupError` we were expecting; but its type is not `LookupError`, it\'s `KeyError`, which is a subclass of `LookupError`, but you specified `assert_exact_type=True`, so subclasses aren\'t acceptable.' wasn't in its message.
    "A `%s` was raised but %s wasn't in its message." %
>>  (self.exception_type.'python_toolbox.cute_testing', repr(self.text))


----------------------------------------------------------------------
Ran 520 tests in 166.450s

FAILED (failures=1, errors=4, skipped=7)
Test failed: <unittest.runner.TextTestResult run=520 errors=4 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=520 errors=4 failures=1>
```

**Comment by cool-RR** [comment]
Thanks for the report. These should be fixed. Does this problem prevent you
from packaging PySnooper? Because python toolbox is used only for testing,
and isn't needed for usage.

**Comment by seqizz** [comment]
Not actually, I'll just disable test phase on the package with a comment. Thanks for the neat tool btw :+1:

**Comment by cool-RR** [comment]
You're welcome 😊

**Comment by cool-RR** [comment]
Fixed.
